// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHAz1jQ9XhzzMN1F6FGP8TQacdjy9t3P4',
    appId: '1:814914078780:web:32565249ee975077015b39',
    messagingSenderId: '814914078780',
    projectId: 'weatherly-e4b75',
    authDomain: 'weatherly-e4b75.firebaseapp.com',
    storageBucket: 'weatherly-e4b75.firebasestorage.app',
    measurementId: 'G-FCDDXVYLBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOH16FIftPTlyHFG4QbA2ftcLZwhsAcFw',
    appId: '1:814914078780:android:08592d77bca8922b015b39',
    messagingSenderId: '814914078780',
    projectId: 'weatherly-e4b75',
    storageBucket: 'weatherly-e4b75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxFQJyzfivQ5R43bYM64C4Khxk-DK4rUo',
    appId: '1:814914078780:ios:b052d936944ee5e1015b39',
    messagingSenderId: '814914078780',
    projectId: 'weatherly-e4b75',
    storageBucket: 'weatherly-e4b75.firebasestorage.app',
    iosBundleId: 'com.example.weatherly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxFQJyzfivQ5R43bYM64C4Khxk-DK4rUo',
    appId: '1:814914078780:ios:b052d936944ee5e1015b39',
    messagingSenderId: '814914078780',
    projectId: 'weatherly-e4b75',
    storageBucket: 'weatherly-e4b75.firebasestorage.app',
    iosBundleId: 'com.example.weatherly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHAz1jQ9XhzzMN1F6FGP8TQacdjy9t3P4',
    appId: '1:814914078780:web:64d8a1d6b55c4e89015b39',
    messagingSenderId: '814914078780',
    projectId: 'weatherly-e4b75',
    authDomain: 'weatherly-e4b75.firebaseapp.com',
    storageBucket: 'weatherly-e4b75.firebasestorage.app',
    measurementId: 'G-8YSMTHBW6H',
  );

}